Repository gritzkoo/nodejs-health-checker, pull requests merged in 2020-10, with the labels that each got.

#7 Implementing CI
  .github/workflows/main.yml
  .github/workflows/test.yaml
  README.md
  package-lock.json
  tests/healthchecker/healthchecker.mocks.ts
Labels: enhancement

#8 feat: including badges: build test coverage and npm publish git action
  .github/CODEOWNERS
  .github/workflows/main.yml
  README.md
  package.json
Labels: documentation, enhancement

#9 docs: update readme.md
  .github/workflows/main.yml
  README.md
Labels: documentation, release:patch

#10 fix: removing configs from memcache service of idle and retries
  src/services/memcache-service.ts
Labels: bug, release:patch
